In [19]:

import random
import numpy as np


In [181]:
aMat = np.array([[1, 1, 0], [0, 1 ,0], [0, 0 ,1]])
bMat =  np.array([[1, 0, 0], [0, 1 ,1], [0, 0 ,1]])
aInv = np.linalg.inv(aMat)
bInv = np.linalg.inv(bMat)
def cMat (x, y):
    return (np.linalg.matrix_power(aInv, x) @ np.linalg.matrix_power(bInv, y) 
            @ np.linalg.matrix_power(aMat, x) @ np.linalg.matrix_power(bMat, y))

cMat(3,3)

numMatrices = 1000
data = np.empty((numMatrices, 3))
matrices = []

In [182]:
for i in range(numMatrices):
    a = random.randint(-100, 100)
    b = random.randint(-100, 100)
    c = random.randint(-100, 100)
    data[i][0] = a
    data[i][1] = b
    data[i][2] = c
    matrices.append(np.array([[1, a, c], [0, 1 ,b], [0, 0 ,1]]))


In [183]:
word = []
coin = random.randint(0,1)
if coin == 1: 
        print("a:")
        word.append("a")
        randomMat = aMat
        print(randomMat)
else: 
        print("b:")
        word.append("b")
        randomMat = bMat
        print(randomMat)
for i in range(10):
    choice = random.randint(0,3)
    if choice == 0: 
        print("a:")
        word.append("a")
        randomMat = randomMat @ aMat
        print(randomMat)
    if choice == 1: 
        print("b:")
        word.append("b")
        randomMat = randomMat @ bMat
        print(randomMat)
    if choice == 2: 
        print("aInv:")
        word.append("aInv")
        randomMat = randomMat @ aInv
        print(randomMat)
    if choice == 3: 
        print("bInv:")
        word.append("bInv")
        randomMat = randomMat @ bInv
        print(randomMat)

a:
[[1 1 0]
 [0 1 0]
 [0 0 1]]
aInv:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
a:
[[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
a:
[[1. 2. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
b:
[[1. 2. 2.]
 [0. 1. 1.]
 [0. 0. 1.]]
aInv:
[[1. 1. 2.]
 [0. 1. 1.]
 [0. 0. 1.]]
bInv:
[[1. 1. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
bInv:
[[ 1.  1.  0.]
 [ 0.  1. -1.]
 [ 0.  0.  1.]]
b:
[[1. 1. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
aInv:
[[1. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
a:
[[1. 1. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [184]:
dest = aMat @ bMat @ aMat @ bMat @ aMat @ bMat


In [185]:
bInv @ aMat @ bMat 

array([[1., 1., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [186]:
# 𝑧75=𝑦−10𝑥−8𝑦5𝑥𝑦5𝑥7
(np.linalg.matrix_power(bInv, 10) @ np.linalg.matrix_power(aInv, 8) @ np.linalg.matrix_power(bMat, 5) 
 @ np.linalg.matrix_power(aMat, 1)) @ np.linalg.matrix_power(bMat, 5) @ np.linalg.matrix_power(aMat, 7)

array([[  1.,   0., -75.],
       [  0.,   1.,   0.],
       [  0.,   0.,   1.]])

In [187]:
cMat(10, 8) 

array([[ 1.,  0., 80.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [188]:
# from Chat GPT 
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Generate some dummy data for training
np.random.seed(42)
X_train = data  # 1000 samples with 3 features each
y_train = np.random.randint(0, 4, size=(1000,))  # Labels 0, 1, 2, or 3

# Convert labels to one-hot encoding
y_train_one_hot = tf.keras.utils.to_categorical(y_train, num_classes=4)

# Define the neural network architecture
model = Sequential()
model.add(Dense(64, input_dim=3, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(4, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train_one_hot, epochs=50, batch_size=32, validation_split=0.2)

# Now you can use the trained model to make predictions on new data
# For example, if you have a new input X_new with shape (1, 3):
# prediction = model.predict(X_new)
# chosen_transformation = np.argmax(prediction)


Epoch 1/50
25/25 [==============================] - 2s 14ms/step - loss: 6.5077 - accuracy: 0.2512 - val_loss: 3.5674 - val_accuracy: 0.2900
Epoch 2/50
25/25 [==============================] - 0s 4ms/step - loss: 2.6290 - accuracy: 0.2625 - val_loss: 2.1905 - val_accuracy: 0.2100
Epoch 3/50
25/25 [==============================] - 0s 4ms/step - loss: 1.8824 - accuracy: 0.2725 - val_loss: 1.9497 - val_accuracy: 0.2500
Epoch 4/50
25/25 [==============================] - 0s 3ms/step - loss: 1.7502 - accuracy: 0.2937 - val_loss: 1.9989 - val_accuracy: 0.2350
Epoch 5/50
25/25 [==============================] - 0s 3ms/step - loss: 1.6593 - accuracy: 0.2850 - val_loss: 1.8964 - val_accuracy: 0.2550
Epoch 6/50
25/25 [==============================] - 0s 3ms/step - loss: 1.6780 - accuracy: 0.3075 - val_loss: 1.8659 - val_accuracy: 0.2100
Epoch 7/50
25/25 [==============================] - 0s 3ms/step - loss: 1.6257 - accuracy: 0.2887 - val_loss: 1.7252 - val_accuracy: 0.2400
Epoch 8/50
25/25 [=

In [195]:
bMat @ aMat


array([[1, 1, 0],
       [0, 1, 1],
       [0, 0, 1]])

In [194]:
aMat @ bMat


array([[1, 1, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [127]:
np.linalg.matrix_power(aMat, 12) @ np.linalg.matrix_power(bMat, 3) 
np.linalg.matrix_power(aMat, 5) @ np.linalg.matrix_power(bMat, 3) @ np.linalg.matrix_power(aMat, 7)

array([[ 1, 12, 15],
       [ 0,  1,  3],
       [ 0,  0,  1]])

In [124]:
np.linalg.matrix_power(aInv @ bInv @ aMat @ bMat, 15)

array([[1, 4, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [131]:
np.linalg.matrix_power(cMat(1,1), 15)

array([[ 1.,  0., 15.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [145]:
cMat(5,5) 

array([[ 1.,  0., 25.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [147]:
np.linalg.matrix_power(bMat, 3) @ np.linalg.matrix_power(aMat, 3)

array([[1, 3, 0],
       [0, 1, 3],
       [0, 0, 1]])

In [171]:
aMat @ bMat @ aInv @ bInv

array([[1., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
cMat(1,1)

array([[1., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [180]:
# testing shortest path when b is smallest: b = 12 a = 20 c = 15
# my guess: 35 is shortest 
np.linalg.matrix_power(aMat @ aMat, 4)


array([[1, 8, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [169]:
np.linalg.matrix_power(aInv, 4)

array([[ 1., -4.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [178]:
cMat(7,5) @ np.linalg.matrix_power(aMat @ aMat, 4)

array([[ 1.,  8., 35.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])