In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np

In [25]:
# code adapted from ChatGPT

# Define your neural network model
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc = nn.Linear(2, 1, bias=False)  # Input size 2, output size 1
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):

        # RUN IT ON A GPU if it exists
        if torch.cuda.is_available():
            x = x.to("cuda")

        x = self.fc(x)
        x = self.sigmoid(x)
        
        return x

def train_model(inputs, desired_outputs, num_epochs=100, learning_rate=0.02, momentum=0.9):
    # Convert inputs and desired_outputs to PyTorch tensors
    inputs = torch.tensor(inputs, dtype=torch.float32)
    desired_outputs = torch.tensor(desired_outputs, dtype=torch.float32)
    
    # Create a DataLoader to handle batching (if needed)
    dataset = TensorDataset(inputs, desired_outputs)
    dataloader = DataLoader(dataset, batch_size=1000, shuffle=True)  # Adjust batch_size as needed
    
    # Initialize the model
    model = SimpleModel()
    
    # Define loss function and optimizer
    criterion = nn.MSELoss()  # Mean Squared Error loss
    optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=momentum)
    
    # Training loop
    for epoch in range(num_epochs):
        total_loss = 0.0
        for batch_inputs, batch_desired_outputs in dataloader:
            optimizer.zero_grad()  # Zero the gradients
            outputs = model(batch_inputs)  # Forward pass
            loss = criterion(outputs, batch_desired_outputs)  # Compute the loss
            loss.backward()  # Backpropagation
            optimizer.step()  # Update the model's parameters
            cur_item = loss.item()
            total_loss += cur_item
            # print(cur_item)
        
        # Print the average loss for this epoch
        print(f"total loss: {total_loss}")
        average_loss = total_loss / len(dataloader)
        for i, param in model.named_parameters():
            print(param)
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {average_loss:.4f}')
    
    # Return the trained model
    return model

In [30]:
input_data = np.random.randint(1, 100, size=(1000, 2))
desired_output = []

for i in input_data:
    desired_output.append([int(i[0] >= i[1])])
    
# Train the model
trained_model = train_model(input_data, desired_output, 500)


total loss: 0.5120950937271118
Parameter containing:
tensor([[0.1329, 0.3066]], requires_grad=True)
Epoch [1/500], Loss: 0.5121
total loss: 0.5120945572853088
Parameter containing:
tensor([[0.1329, 0.3064]], requires_grad=True)
Epoch [2/500], Loss: 0.5121
total loss: 0.5120934247970581
Parameter containing:
tensor([[0.1329, 0.3061]], requires_grad=True)
Epoch [3/500], Loss: 0.5121
total loss: 0.512091875076294
Parameter containing:
tensor([[0.1328, 0.3057]], requires_grad=True)
Epoch [4/500], Loss: 0.5121
total loss: 0.5120898485183716
Parameter containing:
tensor([[0.1328, 0.3053]], requires_grad=True)
Epoch [5/500], Loss: 0.5121
total loss: 0.5120874047279358
Parameter containing:
tensor([[0.1328, 0.3048]], requires_grad=True)
Epoch [6/500], Loss: 0.5121
total loss: 0.5120846629142761
Parameter containing:
tensor([[0.1328, 0.3042]], requires_grad=True)
Epoch [7/500], Loss: 0.5121
total loss: 0.5120815634727478
Parameter containing:
tensor([[0.1328, 0.3036]], requires_grad=True)
Epoch

In [14]:
# Test the trained model (you can use new input data)
test_input = torch.tensor([[10, 20], [2, 1], [3, 5]], dtype=torch.float32)
predictions = trained_model(test_input)
print(predictions)

tensor([[4.8944e-04],
        [6.8569e-01],
        [1.7970e-01]], grad_fn=<SigmoidBackward0>)


In [15]:
trained_model.named_parameters()

<generator object Module.named_parameters at 0x0000016E17EBB140>

In [16]:
for i, param in trained_model.named_parameters():
    print(i)
    print(param)

fc.weight
Parameter containing:
tensor([[ 0.7741, -0.7681]], requires_grad=True)
