In [19]:

import random
import numpy as np


In [109]:
aMat = np.array([[1, 1, 0], [0, 1 ,0], [0, 0 ,1]])
bMat =  np.array([[1, 0, 0], [0, 1 ,1], [0, 0 ,1]])
aInv = np.linalg.inv(aMat)
bInv = np.linalg.inv(bMat)
def cMat (x, y):
    return (np.linalg.matrix_power(bInv, x) @ np.linalg.matrix_power(aInv, y) 
            @ np.linalg.matrix_power(bMat, x) @ np.linalg.matrix_power(aMat, x))

cMat(3,3)

numMatrices = 1000
data = np.empty((numMatrices, 3))
matrices = []

In [110]:
for i in range(numMatrices):
    a = random.randint(-100, 100)
    b = random.randint(-100, 100)
    c = random.randint(-100, 100)
    data[i][0] = a
    data[i][1] = b
    data[i][2] = c
    matrices.append(np.array([[1, a, c], [0, 1 ,b], [0, 0 ,1]]))


array([[  0., -23.,  55.],
       [-35.,  22.,  19.],
       [ 81., -96.,  -3.],
       ...,
       [ 58.,  43.,  42.],
       [-37., -56.,  61.],
       [-86.,  62., -21.]])

In [69]:
word = []
coin = random.randint(0,1)
if coin == 1: 
        print("a:")
        word.append("a")
        randomMat = aMat
        print(randomMat)
else: 
        print("b:")
        word.append("b")
        randomMat = bMat
        print(randomMat)
for i in range(10):
    choice = random.randint(0,3)
    if choice == 0: 
        print("a:")
        word.append("a")
        randomMat = randomMat @ aMat
        print(randomMat)
    if choice == 1: 
        print("b:")
        word.append("b")
        randomMat = randomMat @ bMat
        print(randomMat)
    if choice == 2: 
        print("aInv:")
        word.append("aInv")
        randomMat = randomMat @ aInv
        print(randomMat)
    if choice == 3: 
        print("bInv:")
        word.append("bInv")
        randomMat = randomMat @ bInv
        print(randomMat)

a:
[[1 1 0]
 [0 1 0]
 [0 0 1]]
b:
[[1 1 1]
 [0 1 1]
 [0 0 1]]
aInv:
[[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
bInv:
[[1. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
a:
[[1. 1. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
a:
[[1. 2. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
b:
[[1. 2. 3.]
 [0. 1. 1.]
 [0. 0. 1.]]
bInv:
[[1. 2. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
b:
[[1. 2. 3.]
 [0. 1. 1.]
 [0. 0. 1.]]
aInv:
[[1. 1. 3.]
 [0. 1. 1.]
 [0. 0. 1.]]
a:
[[1. 2. 3.]
 [0. 1. 1.]
 [0. 0. 1.]]


In [76]:
dest = aMat @ bMat @ aMat @ bMat @ aMat @ bMat


In [85]:
bInv @ aMat @ bMat 

array([[1., 1., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
# 𝑧75=𝑦−10𝑥−8𝑦5𝑥𝑦5𝑥7
(np.linalg.matrix_power(bInv, 10) @ np.linalg.matrix_power(aInv, 8) @ np.linalg.matrix_power(bMat, 5) 
 @ np.linalg.matrix_power(aMat, 1)) @ np.linalg.matrix_power(bMat, 5) @ np.linalg.matrix_power(aMat, 7)

array([[  1.,   0., -75.],
       [  0.,   1.,   0.],
       [  0.,   0.,   1.]])

In [93]:
cMat(10, 8) 

array([[  1.,   2., -80.],
       [  0.,   1.,   0.],
       [  0.,   0.,   1.]])

In [111]:
# from Chat GPT 
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Generate some dummy data for training
np.random.seed(42)
X_train = data  # 1000 samples with 3 features each
y_train = np.random.randint(0, 4, size=(1000,))  # Labels 0, 1, 2, or 3

# Convert labels to one-hot encoding
y_train_one_hot = tf.keras.utils.to_categorical(y_train, num_classes=4)

# Define the neural network architecture
model = Sequential()
model.add(Dense(64, input_dim=3, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(4, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train_one_hot, epochs=50, batch_size=32, validation_split=0.2)

# Now you can use the trained model to make predictions on new data
# For example, if you have a new input X_new with shape (1, 3):
# prediction = model.predict(X_new)
# chosen_transformation = np.argmax(prediction)


Epoch 1/50
25/25 [==============================] - 1s 9ms/step - loss: 12.3151 - accuracy: 0.2488 - val_loss: 5.5291 - val_accuracy: 0.2250
Epoch 2/50
25/25 [==============================] - 0s 2ms/step - loss: 3.3912 - accuracy: 0.2688 - val_loss: 2.4442 - val_accuracy: 0.2600
Epoch 3/50
25/25 [==============================] - 0s 2ms/step - loss: 2.1091 - accuracy: 0.2837 - val_loss: 1.8848 - val_accuracy: 0.2600
Epoch 4/50
25/25 [==============================] - 0s 2ms/step - loss: 1.7399 - accuracy: 0.2812 - val_loss: 1.7112 - val_accuracy: 0.2550
Epoch 5/50
25/25 [==============================] - 0s 2ms/step - loss: 1.6201 - accuracy: 0.2887 - val_loss: 1.6450 - val_accuracy: 0.2850
Epoch 6/50
25/25 [==============================] - 0s 2ms/step - loss: 1.5855 - accuracy: 0.3113 - val_loss: 1.7050 - val_accuracy: 0.2250
Epoch 7/50
25/25 [==============================] - 0s 3ms/step - loss: 1.5482 - accuracy: 0.2825 - val_loss: 1.6696 - val_accuracy: 0.2850
Epoch 8/50
25/25 [=